# zshenv

# don't load any zsh config from /etc
unsetopt GLOBAL_RCS

# zsh variables
export ZSH_DIR="$HOME/.zsh"
export ZGEN_DIR="$HOME/.zgen"

# functions used throughout config
source "$ZSH_DIR/zshlib"

# environment variables
export LANG="${LANG:-en_GB.UTF-8}"
export TZ=Europe/London
export EDITOR=vim
export PAGER=less
export LESS='-R -i -M'
export NVM_COMPLETION=true

# paths
typeset -U path
path=(
    "$HOME/bin"
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    "$path[@]"
)

# fzf
if _is_callable fzf; then
    export FZF_DEFAULT_COMMAND='fd --type f'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi
