# zshrc

if [[ ! -d $ZGEN_DIR ]]; then
    git clone https://github.com/tarjoilija/zgen.git $ZGEN_DIR
fi

_source "$ZGEN_DIR/zgen.zsh"

# run `zgen reset` after adding any new loads
if ! zgen saved; then
    echo "Creating zgen save ..."

    # node version manager
    zgen load lukechilds/zsh-nvm

    # completion
    zgen oh-my-zsh lib/completion.zsh
    zgen load zsh-users/zsh-completions

    # terminal window/tab title support
    zgen oh-my-zsh lib/termsupport.zsh

    # suggest commands as you type based on history
    zgen load zsh-users/zsh-autosuggestions

    zgen save
fi

# use emacs key bindings
bindkey -e

# OS-specific aliases, exports, etc.
case "$OSTYPE" in
    darwin*)  _source macos.zsh ;;
    freebsd*) _source freebsd.zsh ;;
    linux*)   _source linux.zsh ;;
esac

_source aliases.zsh
_source completion.zsh
_source config.zsh
_source prompt.zsh

# local additions or overwrites
_source "$HOME/.zshrc.local"
